### ISSUE TITLE
The following modules are missing or built with a different engine version

### ISSUE THREAD

**Issue by Soldream0** [Arisego/UnrealLive2D#16]
First02(name my project) could not be compiled. Try rebuilding from source manually.

UE 4.27.2
Update with UE4.27 release
[First02.log](https://github.com/Arisego/UnrealLive2D/files/9896372/First02.log)

I also don't quite understand how to install. Could you explain in more detail?

**Comment by Arisego** [comment]
According to this log, it appears that cubism sdk is missing:

```
WARNING: Library 'C:\Prochee\Unreal Engine Project\First02\Plugins\UnrealLive2D-1.1.2\Source\ThirdParty\CubismLibrary/lib/windows/x86_64/142/Live2DCubismCore_MTd.lib' was not resolvable to a file when used in Module 'UnrealLive2D', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
```

I'm not sure if the compile errors in the following lines are related to this because they're not displaying correctly.

Two steps are involved in installing the plugin:

1. Download the plugin and place it in the "/Plugins/" directory of the project.
2. Download the corresponding version of cubism sdk and put it into cubismlibrary direcotry in plugin: `UnrealLive2D/Source/ThirdParty/CubismLibrary/`

You may want to take a look at this [sample project](https://github.com/Arisego/Live2DTest) since it has already been tested to work in my own environment and has completed all installation steps.

**Comment by Soldream0** [comment]
Thanks for the answer.
I installed sdk and it solved some of the errors. But I still can't open the project.
[MyProject.log](https://github.com/Arisego/UnrealLive2D/files/9900213/MyProject.log)

**Comment by Soldream0** [comment]
I solved it by copying the folder:
Plugins\UnrealLive2D-1.1.2\Source\ThirdParty\CubismLibrary\lib

Instead of:
Plugins\UnrealLive2D-1.1.2\Source\ThirdParty\CubismLibrary

I created a new project and added only the lib folder to it. (Not the whole sdk). Does this mean I don't need the whole sdk? Is sdk required or just the lib folder is enough?

(p.s. How about adding this to the description?)

**Comment by Arisego** [comment]
I'm glad to hear that.

And, thanks for your advice, the installation section of the document is not clear enough, I will try to add more details into it when I got time. 

This plugin is separated from one of my abandoned projects, I released it to help giving a start point for integrating Live2D into Unreal Engine. As a result, it lacks some optimization and is not functional enough. You may need to take a deeper look into Live2D's SDK interface if you intend to use it in a production project.
